---
- name: kubectl, kubectx, etc.
  hosts: localhost
  tasks:
    - name: Install zsh (Mac)
      homebrew:
        name: kubectl
        state: present
      when: ansible_facts.os_family == 'Darwin'

    - name: Install kubectx/kubens (Mac)
      homebrew:
        name: kubectx
        state: present
      when: ansible_facts.os_family == 'Darwin'
